### ISSUE TITLE
Breaks with xf86-input-libinput 1.2.0-1

### ISSUE THREAD

**Issue by fidasx** [tkkcc/libinput_patch#3]
Hello after updating xf86-input-libinput over 1.1.0-1 it doesn't work propably has something to do with the high resolution scrolling? https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/652/

**Comment by tkkcc** [comment]
Confirmed. But I currently do not have time to make this work.

**Comment by tkkcc** [comment]
Fixed. Thanks!

**Comment by fidasx** [comment]
ty you are amazing
